// <auto-generated />
using System;
using HCAMiniEHR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCAMiniEHR.Migrations
{
    [DbContext(typeof(HCAMiniEHRDbContext))]
    [Migration("20260111151651_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Healthcare")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment", "Healthcare");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9747),
                            DoctorId = 5,
                            PatientId = 1,
                            Reason = "General Checkup",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9759),
                            DoctorId = 1,
                            PatientId = 2,
                            Reason = "Chest Pain",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9761),
                            DoctorId = 2,
                            PatientId = 3,
                            Reason = "Knee Pain",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9763),
                            DoctorId = 3,
                            PatientId = 4,
                            Reason = "Skin Allergy",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9765),
                            DoctorId = 4,
                            PatientId = 5,
                            Reason = "Headache",
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditId");

                    b.ToTable("AuditLog", "Healthcare");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctor", "Healthcare");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9607),
                            FullName = "Dr. Ananya Rao",
                            IsActive = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            DoctorId = 2,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9619),
                            FullName = "Dr. Vikram Singh",
                            IsActive = true,
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            DoctorId = 3,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9620),
                            FullName = "Dr. Meera Iyer",
                            IsActive = true,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            DoctorId = 4,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9621),
                            FullName = "Dr. Karthik N",
                            IsActive = true,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            DoctorId = 5,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9622),
                            FullName = "Dr. Pooja Sharma",
                            IsActive = true,
                            Specialization = "General Medicine"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.LabOrder", b =>
                {
                    b.Property<int>("LabOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabOrderId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LabOrderId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("LabOrder", "Healthcare");

                    b.HasData(
                        new
                        {
                            LabOrderId = 1,
                            AppointmentId = 1,
                            OrderedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9781),
                            Status = "Pending",
                            TestName = "Blood Test"
                        },
                        new
                        {
                            LabOrderId = 2,
                            AppointmentId = 1,
                            OrderedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9782),
                            Status = "Pending",
                            TestName = "Urine Test"
                        },
                        new
                        {
                            LabOrderId = 3,
                            AppointmentId = 1,
                            OrderedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9783),
                            Status = "Ordered",
                            TestName = "Lipid Profile"
                        },
                        new
                        {
                            LabOrderId = 4,
                            AppointmentId = 2,
                            OrderedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9784),
                            Status = "Completed",
                            TestName = "ECG"
                        },
                        new
                        {
                            LabOrderId = 5,
                            AppointmentId = 3,
                            OrderedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9785),
                            Status = "Pending",
                            TestName = "X-Ray"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patient", "Healthcare");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9710),
                            DateOfBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ravi Kumar",
                            Gender = "Male"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9718),
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sita Devi",
                            Gender = "Female"
                        },
                        new
                        {
                            PatientId = 3,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9719),
                            DateOfBirth = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Amit Shah",
                            Gender = "Male"
                        },
                        new
                        {
                            PatientId = 4,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9721),
                            DateOfBirth = new DateTime(1997, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Neha Verma",
                            Gender = "Female"
                        },
                        new
                        {
                            PatientId = 5,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9723),
                            DateOfBirth = new DateTime(1985, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kiran Rao",
                            Gender = "Male"
                        },
                        new
                        {
                            PatientId = 6,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9724),
                            FullName = "Priya Nair",
                            Gender = "Female"
                        },
                        new
                        {
                            PatientId = 7,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9725),
                            DateOfBirth = new DateTime(1999, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Arjun Patel",
                            Gender = "Male"
                        },
                        new
                        {
                            PatientId = 8,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9726),
                            FullName = "Lakshmi Iyer",
                            Gender = "Female"
                        },
                        new
                        {
                            PatientId = 9,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9727),
                            DateOfBirth = new DateTime(1978, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Suresh Babu",
                            Gender = "Male"
                        },
                        new
                        {
                            PatientId = 10,
                            CreatedAt = new DateTime(2026, 1, 11, 20, 46, 51, 168, DateTimeKind.Local).AddTicks(9728),
                            DateOfBirth = new DateTime(2000, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Divya Reddy",
                            Gender = "Female"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.HasOne("HCAMiniEHR.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HCAMiniEHR.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.LabOrder", b =>
                {
                    b.HasOne("HCAMiniEHR.Models.Appointment", "Appointment")
                        .WithMany("LabOrders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
